/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagePageIdIndexRouteImport } from './routes/page/$pageId/index'
import { Route as BlogsBlogIdIndexRouteImport } from './routes/blogs/$blogId/index'
import { Route as authRegisterIndexRouteImport } from './routes/(auth)/register/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagePageIdIndexRoute = PagePageIdIndexRouteImport.update({
  id: '/page/$pageId/',
  path: '/page/$pageId/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlogIdIndexRoute = BlogsBlogIdIndexRouteImport.update({
  id: '/blogs/$blogId/',
  path: '/blogs/$blogId/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/(auth)/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof authRegisterIndexRoute
  '/blogs/$blogId': typeof BlogsBlogIdIndexRoute
  '/page/$pageId': typeof PagePageIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof authRegisterIndexRoute
  '/blogs/$blogId': typeof BlogsBlogIdIndexRoute
  '/page/$pageId': typeof PagePageIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/blogs/$blogId/': typeof BlogsBlogIdIndexRoute
  '/page/$pageId/': typeof PagePageIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/register' | '/blogs/$blogId' | '/page/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/register' | '/blogs/$blogId' | '/page/$pageId'
  id:
    | '__root__'
    | '/'
    | '/(auth)/register/'
    | '/blogs/$blogId/'
    | '/page/$pageId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
  BlogsBlogIdIndexRoute: typeof BlogsBlogIdIndexRoute
  PagePageIdIndexRoute: typeof PagePageIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/$pageId/': {
      id: '/page/$pageId/'
      path: '/page/$pageId'
      fullPath: '/page/$pageId'
      preLoaderRoute: typeof PagePageIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$blogId/': {
      id: '/blogs/$blogId/'
      path: '/blogs/$blogId'
      fullPath: '/blogs/$blogId'
      preLoaderRoute: typeof BlogsBlogIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
  BlogsBlogIdIndexRoute: BlogsBlogIdIndexRoute,
  PagePageIdIndexRoute: PagePageIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
