/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagePageIdIndexRouteImport } from './routes/page/$pageId/index'
import { Route as BlogsCreateIndexRouteImport } from './routes/blogs/create/index'
import { Route as BlogsBlogIdIndexRouteImport } from './routes/blogs/$blogId/index'
import { Route as authRegisterIndexRouteImport } from './routes/(auth)/register/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as BlogsBlogIdUpdateIndexRouteImport } from './routes/blogs/$blogId/update/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagePageIdIndexRoute = PagePageIdIndexRouteImport.update({
  id: '/page/$pageId/',
  path: '/page/$pageId/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsCreateIndexRoute = BlogsCreateIndexRouteImport.update({
  id: '/blogs/create/',
  path: '/blogs/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlogIdIndexRoute = BlogsBlogIdIndexRouteImport.update({
  id: '/blogs/$blogId/',
  path: '/blogs/$blogId/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/(auth)/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlogIdUpdateIndexRoute = BlogsBlogIdUpdateIndexRouteImport.update({
  id: '/blogs/$blogId/update/',
  path: '/blogs/$blogId/update/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/blogs/$blogId': typeof BlogsBlogIdIndexRoute
  '/blogs/create': typeof BlogsCreateIndexRoute
  '/page/$pageId': typeof PagePageIdIndexRoute
  '/blogs/$blogId/update': typeof BlogsBlogIdUpdateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/blogs/$blogId': typeof BlogsBlogIdIndexRoute
  '/blogs/create': typeof BlogsCreateIndexRoute
  '/page/$pageId': typeof PagePageIdIndexRoute
  '/blogs/$blogId/update': typeof BlogsBlogIdUpdateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/blogs/$blogId/': typeof BlogsBlogIdIndexRoute
  '/blogs/create/': typeof BlogsCreateIndexRoute
  '/page/$pageId/': typeof PagePageIdIndexRoute
  '/blogs/$blogId/update/': typeof BlogsBlogIdUpdateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/blogs/$blogId'
    | '/blogs/create'
    | '/page/$pageId'
    | '/blogs/$blogId/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/blogs/$blogId'
    | '/blogs/create'
    | '/page/$pageId'
    | '/blogs/$blogId/update'
  id:
    | '__root__'
    | '/'
    | '/(auth)/login/'
    | '/(auth)/register/'
    | '/blogs/$blogId/'
    | '/blogs/create/'
    | '/page/$pageId/'
    | '/blogs/$blogId/update/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
  BlogsBlogIdIndexRoute: typeof BlogsBlogIdIndexRoute
  BlogsCreateIndexRoute: typeof BlogsCreateIndexRoute
  PagePageIdIndexRoute: typeof PagePageIdIndexRoute
  BlogsBlogIdUpdateIndexRoute: typeof BlogsBlogIdUpdateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/$pageId/': {
      id: '/page/$pageId/'
      path: '/page/$pageId'
      fullPath: '/page/$pageId'
      preLoaderRoute: typeof PagePageIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/create/': {
      id: '/blogs/create/'
      path: '/blogs/create'
      fullPath: '/blogs/create'
      preLoaderRoute: typeof BlogsCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$blogId/': {
      id: '/blogs/$blogId/'
      path: '/blogs/$blogId'
      fullPath: '/blogs/$blogId'
      preLoaderRoute: typeof BlogsBlogIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$blogId/update/': {
      id: '/blogs/$blogId/update/'
      path: '/blogs/$blogId/update'
      fullPath: '/blogs/$blogId/update'
      preLoaderRoute: typeof BlogsBlogIdUpdateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLoginIndexRoute: authLoginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
  BlogsBlogIdIndexRoute: BlogsBlogIdIndexRoute,
  BlogsCreateIndexRoute: BlogsCreateIndexRoute,
  PagePageIdIndexRoute: PagePageIdIndexRoute,
  BlogsBlogIdUpdateIndexRoute: BlogsBlogIdUpdateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
